In [1]:
import numpy as np
np.random.seed(42)

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
    

In [4]:
## AND Dataset


In [5]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[0],[0],[1]])
print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [6]:
W1=np.random.randn(2,4)
b1=np.zeros((1,4))
W2=np.random.randn(4,1)
b2=np.zeros((1,1))
print(W1.shape,W2.shape)

(2, 4) (4, 1)


In [7]:
z1=X@W1+b1
a1=sigmoid(z1)
z2=a1@W2+b2
prediction=sigmoid(z2)
print(prediction)

[[0.39459663]
 [0.33849512]
 [0.32609598]
 [0.29208992]]


In [8]:
error=prediction-y
print(error)

[[ 0.39459663]
 [ 0.33849512]
 [ 0.32609598]
 [-0.70791008]]


In [9]:
delta2=error*prediction*(1-prediction)
delta1=(delta2@W2.T)*a1*(1-a1)
print(delta2)
print(delta1)

[[ 0.09426524]
 [ 0.07579453]
 [ 0.071662  ]
 [-0.14637697]]
[[-0.01106378  0.01278614 -0.01092105 -0.01097553]
 [-0.00877507  0.01014115 -0.00497707 -0.00764323]
 [-0.00791269  0.00967393 -0.0074891  -0.00490511]
 [ 0.01688734 -0.01918181  0.00596133  0.00569014]]


In [10]:
lr=0.1
W2-=lr*(a1.T@delta2)
b2-=lr*np.sum(delta2,axis=0,keepdims=True)
W1-=lr*(X.T@delta1)
b1-=lr*np.sum(delta1,axis=0,keepdims=True)
print("Weights Updated!")

Weights Updated!
