In [2]:
import numpy as np

#create arrays
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [2]:
import numpy as np
b=np.array([1,2,3])
c=np.array([4,5,6])

print("Addition: ",b+c)
print("Substraction: ",b-c)
print("Multiplication: ",b*c)
print("Division: ",b/c)
print("Power: ",b**c)



Addition:  [5 7 9]
Substraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Power:  [  1  32 729]


In [4]:
import numpy as np
#Slicing

ar=np.array([10,20,30,40,50])
print(ar[1:4])
print(ar[:3])
print(ar[1:])
print(ar[2:3])

[20 30 40]
[10 20 30]
[20 30 40 50]
[30]


In [5]:
import numpy as np
#indexing

arr=np.array([1,2,3,4,5])
print(arr[2])
print(arr[-1])

3
5


In [9]:
import numpy as np
#Reshaping

d=np.array([[1,2,3],[4,5,6]])
e=d.reshape(3,2)
print(e)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
import numpy as np


In [2]:

import numpy as np
marks=np.array([70,80,60,90,45,67,87,43,88,99])
print(marks)

[70 80 60 90 45 67 87 43 88 99]


In [6]:
import numpy as np
arr=np.array([2,3,4,5,6,7])

print("Datatype: ",arr.dtype)
print("Size: ",arr.size)
print("Number of dimensions: ",arr.ndim)
print("Shape: ",arr.shape)

Datatype:  int64
Size:  6
Number of dimensions:  1
Shape:  (6,)


In [7]:
import numpy as np
marks=np.array([70,30,60,90,45,67,27,43,88,99])

print("Marks greater than 60: ",marks[marks>60])

Marks greater than 60:  [70 90 67 88 99]


In [10]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
print("3x3 Matrix: ",arr.reshape(3,3))

3x3 Matrix:  [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
import numpy as np
random_arr=np.random.random(10)
print("Random 10 numbers: ",random_arr)

Random 10 numbers:  [0.86110884 0.43254025 0.07956634 0.97058886 0.33211866 0.41285327
 0.79575038 0.29111275 0.54879379 0.38760187]


In [13]:
#Broadcasting +5 to all elements
import numpy as np
arr=np.array([1,2,3])
print("After broadcasting: ",arr+5)

After broadcasting:  [6 7 8]


In [14]:
#FIND SQUARE OF ALL ELEMENTS
import numpy as np
arr=np.array([1,2,3])
print("After broadcasting: ",arr**2)

After broadcasting:  [1 4 9]


In [16]:
import numpy as np
print("Numbers from 1 to 20: ",np.arange(1,21))

Numbers from 1 to 20:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [17]:
import numpy as np
arr=np.array([2,3,4,5])
print("Maximum value: ",np.max(arr))
print("Minimum value: ",np.min(arr))
print("Averaeg value: ",np.mean(arr))



Maximum value:  5
Minimum value:  2
Averaeg value:  3.5


In [18]:
import numpy as np
arr=np.array([6,14,5,5])
print("Even Numbers: ",arr[arr%2==0])


Even Numbers:  [ 6 14]


In [25]:
#Create a 4×4 matrix filled with numbers from 1 to 16.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17])
print("4x4 matrix : ",arr.reshape(4,4))


4x4 matrix :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 17]]


In [26]:
#Find the sum of each row and sum of each column.


In [27]:
#Generate an array of 15 random integers between 1 and 100.
import numpy as np
arr=np.random.randint([1,101,15])
print(arr)

[ 0 20 14]


In [29]:
#Sort the array in ascending and descending order.
import numpy as np
arr=([2,9,91,67,32,23,33])
print("Asending Order: ",np.sort(arr))
print("desending  Order: ",np.sort(arr)[::-1])


Asending Order:  [ 2  9 23 32 33 67 91]
desending  Order:  [91 67 33 32 23  9  2]


In [30]:
#Replace all values greater than 50 with 0.

In [31]:
#Find the index position of the largest element.


In [35]:
#Multiply all elements of the array by 2 using broadcasting.
arr=np.array([3,4,5])
print("Square: ",arr*2)
#cube
print("Cube: ",arr*3)

Square:  [ 6  8 10]
Cube:  [ 9 12 15]


In [37]:
#Create two arrays and perform:(Addition,Subtraction,Multiplication,Division)
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print("Addition: ",a+b)
print("Substraction: ",a-b)
print("Multiplication: ",a*b)
print("Division: ",a/b)


Addition:  [5 7 9]
Substraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


In [38]:
#Create a 5×5 identity matrix. Find the transpose of a 3×3 matrix.



In [ ]:
Calculate the mean, median, and standard deviation of an array.